packages:
  - "react"
  - "next"
  - "abis"
  - "styles"
  - "lib"
  - "node"
  - "types"
  - "viem"
  - "react-wagmi"
  - "mongo"
  - "blockchain"
allowBuilds:
  bufferutil: true
  esbuild: true
  keccak: true
  sharp: false
  utf-8-validate: true
minimumReleaseAgeExclude:
  - "@a2zb/lib@1.0.1"
